import { useState } from 'react';
import { glossary } from '../data/glossary';
import { assessmentQuestions } from '../data/assessment';
import { sources } from '../data/lessons';
import { Choices, Seal } from '../components/UI';
import { Quiz } from '../components/Quiz';
import { ReadButton } from '../components/Speech';

export function Glossary() {
  const [query, setQuery] = useState('');
  const matches = glossary.filter(g => `${g.term} ${g.definition}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.term.localeCompare(b.term));
  return <><header className="page-heading"><span className="eyebrow">THE LITTLE DICTIONARY</span><h1>Big words.<br/><em>Small explanations.</em></h1><p>A friendly place to untangle an unfamiliar term.</p></header><label className="search-field"><span aria-hidden="true">⌕</span><input type="search" value={query} placeholder="Try ‘private key’, ‘SAN’, or ‘trust’…" aria-label="Search glossary" onChange={e => setQuery(e.target.value)}/></label><p className="result-count" aria-live="polite">{matches.length} {matches.length === 1 ? 'term' : 'terms'} found</p><div className="glossary-grid">{matches.map(g => <article className="glossary-card" key={g.term}><h2>{g.term}</h2><p>{g.definition}</p><ReadButton id={`glossary-${g.term}`} text={`${g.term}. ${g.definition}`} label={`Listen: ${g.term}`}/><a href={`#/learn/${g.lesson}`}>See it in the story <span aria-hidden="true">↗</span></a></article>)}</div>{matches.length === 0 && <div className="empty-state"><h2>No matching terms yet.</h2><p>Try a shorter word, or <button className="text-button" onClick={() => setQuery('')}>show all terms</button>.</p></div>}</>;
}
export function About({ resetProgress }: { resetProgress: () => void }) {
  const [reset, setReset] = useState(false);
  return <><header className="page-heading"><span className="eyebrow">BEHIND THE LITTLE BOOK</span><h1>Made for your<br/><em>“oh, now I get it.”</em></h1><p>Certificates are easier to understand when you can see the decisions, change the details, and ask why.</p></header><section className="about-card"><Seal/><div><h2>A story you can take apart.</h2><p>Signed, Explained is a static, interactive guide to X.509 certificates and TLS. Begin with Browser Bea’s bakery visit, then explore public issuers, private CAs, mutual TLS, and a GitLab deployment.</p><p>Simple stories are paired with technical notes. The artwork, narration, and simulations are original. The teaching inspiration is <a href="https://thesecretlivesofdata.com/raft/" target="_blank" rel="noreferrer">The Secret Lives of Data’s Raft explanation</a>.</p><h3>What the simulations mean</h3><p>All names, dates, signatures, and keys are fictional. These are deterministic learning models, not real cryptography or a certificate validator. The app never uploads certificates, installs trust, executes OpenSSL, or changes your server. Results do not assess a live system.</p><h3>Narration included</h3><p>The built-in English narration was generated locally using Piper and its LJ Speech voice model. <a href={`${import.meta.env.BASE_URL}audio/CREDITS.md`} target="_blank" rel="noreferrer">Voice credits and model sources</a>.</p><h3>Your progress stays here</h3><p>Completed chapter IDs and your playback speed are saved in this browser’s local storage. There are no accounts or analytics. Synthetic narration is bundled as audio files served by this website, so no installed speech voice or external speech service is needed. If storage is unavailable, the lessons still work.</p><button className="secondary" onClick={() => { resetProgress(); setReset(true); }}>Reset my chapter progress</button>{reset && <p role="status">Chapter progress cleared.</p>}</div></section><section className="sources-section"><span className="eyebrow">KEEP EXPLORING</span><h2>Go straight to the sources.</h2><p>Primary references for the concepts in this book. Real clients and issuers apply additional policies.</p><div className="source-grid">{Object.values(sources).map(s => <a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title}<span aria-hidden="true">↗</span></a>)}</div></section></>;
}

export function FinalCheck() {
  const [mode, setMode] = useState('Public CA'); const [passed, setPassed] = useState<string[]>([]);
  const models = ['Public CA', 'Private CA', 'Self-signed'] as const;
  const questions = assessmentQuestions(mode);
  return <><header className="page-heading"><span className="eyebrow">PUT THE PIECES TOGETHER</span><h1>Can you explain<br/><em>the little card?</em></h1><p>Try four questions for each trust model. Hints explain the answer, so you can learn as you go.</p></header><Choices label="Assessment trust model" options={models} value={mode} onChange={setMode}/><div className="assessment-progress"><Seal small/><span>{passed.length} / 12 concepts connected</span></div><div className="assessment-grid">{questions.map((q, i) => <Quiz key={`${mode}-${i}`} {...q} onCorrect={() => setPassed(p => p.includes(`${mode}-${i}`) ? p : [...p, `${mode}-${i}`])}/>)}</div>{passed.length === 12 && <div className="completion-banner"><Seal/><div><h2>You’ve connected the whole story.</h2><p>Explain it to someone else: who signed, who trusts, where the key lives, and which checks can still fail.</p><a className="primary" href="#/playground">Try the trust lab →</a></div></div>}</>;
}
