import { useState } from 'react';
import { Actor, Arrow, Choices, Experiment, Seal, Status, Toggle } from '../components/UI';
import type { SceneProps } from './Foundations';

export function Issuance({ step, onInteract }: SceneProps) {
  const [mode, setMode] = useState('Public CA · ZeroSSL');
  const [method, setMethod] = useState('DNS CNAME');
  const [proof, setProof] = useState(false); const [issued, setIssued] = useState(false);
  const [trusted, setTrusted] = useState(false); const [chain, setChain] = useState(true);
  const [key, setKey] = useState(true); const [name, setName] = useState(true); const [valid, setValid] = useState(true);
  const publicCA = mode === 'Public CA · ZeroSSL'; const self = mode === 'Self-signed server';
  const accepted = publicCA || trusted;
  const stages = ['Name + key', 'CSR', publicCA ? 'Domain proof' : self ? 'Own identity' : 'CA approval', 'Sign', 'Install', 'Client trust', 'Renew'];
  const change = (fn: () => void) => { onInteract(); fn(); };
  return <><div className="scene"><Choices label="Issuance model" options={['Public CA · ZeroSSL', 'Private CA', 'Self-signed server']} value={mode} onChange={v => change(() => { setMode(v); setIssued(false); setProof(false); setTrusted(false); setChain(true); setKey(true); setName(true); setValid(true); })}/>
    <div className="issuance-progress">{stages.map((label, i) => <div key={label} className={i === step ? 'current' : i < step ? 'done' : ''}><span>{i < step ? '✓' : i + 1}</span><small>{label}</small></div>)}</div>
    <div className="actor-row"><Actor kind="shop" name="bakery.example" caption="Server private key stays here" active={step < 2 || step >= 4}/><Arrow reverse={step >= 3}>{step < 3 ? 'Public key + request' : 'Signed public certificate'}</Arrow><Actor kind={self ? 'shop' : 'office'} name={publicCA ? 'Public issuing CA' : self ? 'The same server' : 'Your private CA'} caption={self ? 'Signs using its own key' : 'Issuer private key stays here'} active={step >= 2 && step < 4}/></div>
    <div className="issuance-note">{publicCA ? <><strong>ZeroSSL-style domain verification</strong><p>{method === 'DNS CNAME' ? 'Publish the requested CNAME record. The CA looks it up to check control of the name.' : 'Publish the requested file under the domain’s verification path. The CA retrieves and checks it.'}</p><code>{method === 'DNS CNAME' ? '_demo.bakery.example → proof.ca.example' : 'http://bakery.example/.well-known/pki-verification/demo.txt'}</code><small>Fictional challenge · illustration of the dashboard/API flow, not an ACME challenge</small></> : <><strong>{self ? 'One server, one self-signed card' : 'Your organization sets issuance policy'}</strong><p>{self ? 'The signer and subject use the same key pair. A stranger’s browser does not automatically accept this identity.' : 'The CA reviews the requested names and purpose. It signs approved server keys, while clients receive only its public trust certificate.'}</p></>}</div>
    {issued ? <><div className="issued-card"><Seal small/><strong>Certificate issued for bakery.example</strong><span>Private server key was not sent to the issuer</span></div><Status ok={accepted && (self || chain) && key && name && valid}>{!accepted ? 'Issued, but untrusted by Bea. Configure the demo client trust below.' : !self && !chain ? 'Issued, but the deployment is missing its intermediate.' : !key ? 'Issued, but the installed private key does not match.' : !name ? 'Trusted issuer, but the requested server name does not match.' : !valid ? 'Trusted issuer, but the certificate has expired.' : 'Ready in this simulation: trust, identity, deployment, and key proof all pass.'}</Status></> : <Status ok="unknown">{self || proof ? 'Ready to sign. Advance to step 4 and issue the demo certificate.' : publicCA ? 'Issuance is waiting for successful domain-control verification.' : 'Issuance is waiting for the private CA’s approval.'}</Status>}
  </div><Experiment>{publicCA && <Choices label="Domain verification method" options={['DNS CNAME', 'HTTP file']} value={method} onChange={v => change(() => { setMethod(v); setProof(false); setIssued(false); })}/>}
    {!self && <Toggle label={publicCA ? 'Publish the correct demo challenge proof' : 'CA approves the names and server purpose'} value={proof} disabled={issued} onChange={v => change(() => setProof(v))}/>}
    <button className="primary" disabled={step < 3 || (!self && !proof) || issued} onClick={() => change(() => setIssued(true))}>{issued ? '✓ Certificate issued' : 'Issue demo certificate'}</button>
    {!publicCA && <Toggle label={self ? 'Explicitly trust this demo leaf in Bea’s client' : 'Install this demo CA’s public trust certificate'} value={trusted} onChange={v => change(() => setTrusted(v))}/>}
    {issued && <div className="control-grid">{!self && <Toggle label="Install intermediate chain" value={chain} onChange={v => change(() => setChain(v))}/>}<Toggle label="Install matching private key" value={key} onChange={v => change(() => setKey(v))}/><Toggle label="Requested name matches SAN" value={name} onChange={v => change(() => setName(v))}/><Toggle label="Certificate is within its lifetime" value={valid} onChange={v => change(() => setValid(v))}/></div>}
    <p>{publicCA ? 'This demo client already accepts the public root. Real compatibility depends on the client’s trust store.' : 'Trust is simulated here. Nothing changes in your browser or operating system.'}</p>
  </Experiment></>;
}

export function MutualTLS({ step, onInteract }: SceneProps) {
  const [mtls, setMTLS] = useState(false); const [client, setClient] = useState('Valid card'); const [allowed, setAllowed] = useState(true);
  const ok = !mtls || client === 'Valid card';
  return <><div className="scene"><div className="actor-row"><Actor name="Browser Bea" caption={mtls ? client : 'No client certificate requested'} active={step === 2} bad={mtls && !ok}/><div className="two-arrows"><Arrow reverse>Server certificate + proof</Arrow>{mtls && <Arrow>Client certificate + proof</Arrow>}</div><Actor kind="server" name="Recipe service" caption="Server identity: verified" active={step === 1}/></div>
    <div className="gates"><div className="gate"><span>01 · TRANSPORT</span><h3>{ok ? '✓ TLS accepted' : '! TLS rejected'}</h3><p>{!mtls ? 'Only the server has a certificate identity.' : ok ? 'Both certificate identities satisfy the demo policies.' : client === 'No card' ? 'The required client certificate is missing.' : 'The server does not trust this client’s issuer.'}</p></div><div className="gate"><span>02 · APPLICATION</span><h3>{!ok ? '— Not reached' : allowed ? '✓ Read recipe allowed' : '! Operation denied'}</h3><p>{!ok ? 'Finish authentication before the request proceeds.' : allowed ? 'The application’s separate access rule permits this action.' : 'A secure connection is not an all-access pass.'}</p></div></div>
  </div><Experiment><Toggle label="Require mutual TLS" value={mtls} onChange={v => { onInteract(); setMTLS(v); }}/>{mtls && <Choices label="Client identity" options={['Valid card', 'No card', 'Untrusted card']} value={client} onChange={v => { onInteract(); setClient(v); }}/>}<Toggle label="Application allows the operation" value={allowed} onChange={v => { onInteract(); setAllowed(v); }}/></Experiment></>;
}

export function Lifecycle({ step, onInteract }: SceneProps) {
  const [day, setDay] = useState(30); const [renewed, setRenewed] = useState(false);
  const [newTrust, setNewTrust] = useState(false); const [newIssuer, setNewIssuer] = useState(false); const [oldTrust, setOldTrust] = useState(true);
  const [revocation, setRevocation] = useState('Good');
  const date = new Date(Date.UTC(2030, 0, 1 + day)).toLocaleDateString('en', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
  const dateOK = renewed ? day >= 75 && day <= 164 : day >= 0 && day <= 89;
  const trustOK = newIssuer ? newTrust : oldTrust;
  const change = (fn: () => void) => { onInteract(); fn(); };
  return <><div className="scene"><div className="calendar-header"><span className="calendar-icon" aria-hidden="true">▦</span><div><span className="eyebrow">OUR LITTLE DEMO CALENDAR</span><h3>{date}</h3><p>Fixed simulated clock · not your computer’s time</p></div><span className="tag">Day {day}</span></div><div className="timeline-label"><span>Jan 1</span><span>Mar 17</span><span>Jun 14</span></div><div className="timeline"><div className="time-window old" style={{ left: '0%', width: '54.3%' }}>Original certificate</div><div className={`time-window renewed ${!renewed ? 'pending' : ''}`} style={{ left: '45.7%', width: '54.3%' }}>Replacement {renewed ? 'deployed' : 'available'}</div><div className="time-cursor" style={{ left: `${Math.max(0, Math.min(100, day / 164 * 100))}%` }}><span>Today</span></div></div>
    <div className="gates"><div className="gate"><span>ACTIVE IDENTITY</span><h3>{renewed ? 'Replacement certificate' : 'Original certificate'}</h3><p>{renewed ? 'Valid Mar 17 – Jun 14, 2030' : 'Valid Jan 1 – Mar 31, 2030'} · {newIssuer ? 'New CA' : 'Original CA'}</p></div><div className="gate"><span>CLIENT TRUST STORE</span><h3>{oldTrust ? 'Original CA' : ''}{oldTrust && newTrust ? ' + ' : ''}{newTrust ? 'New CA' : ''}{!oldTrust && !newTrust ? 'No accepted CA' : ''}</h3><p>Public trust information only</p></div></div>
    <Status ok={!dateOK || !trustOK || revocation === 'Revoked' ? false : revocation === 'Unknown' ? 'unknown' : true}>{!dateOK ? 'Outside the active certificate’s validity window. Check time or deploy the appropriate replacement.' : !trustOK ? 'Issuer transition failed: the active certificate’s CA is not in the client trust store.' : revocation === 'Revoked' ? 'Certificate revoked. Investigate and replace the identity.' : revocation === 'Unknown' ? 'Revocation status unavailable. This demo’s strict policy blocks acceptance.' : 'Time, issuer trust, and simulated revocation checks pass.'}</Status>
    {step >= 4 && <div className="fact-pair"><p><strong>ACME</strong>Automates domain authorization and certificate issuance. Deployment still needs coordination.</p><p><strong>Certificate Transparency</strong>Auditable public issuance logs help detect unexpected certificates. They do not hold private keys.</p></div>}
  </div><Experiment><label className="field">Move through time · {date}<input type="range" min="-10" max="180" value={day} onChange={e => change(() => setDay(Number(e.target.value)))}/></label><Toggle label="Deploy the replacement certificate" value={renewed} onChange={v => change(() => setRenewed(v))}/><details><summary>Try a CA rollover</summary><div className="control-grid"><Toggle label="Client trusts the new CA" value={newTrust} onChange={v => change(() => setNewTrust(v))}/><Toggle label="Server uses a certificate from the new CA" value={newIssuer} onChange={v => change(() => setNewIssuer(v))}/><Toggle label="Client still trusts the original CA" value={oldTrust} onChange={v => change(() => setOldTrust(v))}/></div><p>First add new trust, then switch the identity, then retire old trust. Try changing the order.</p></details><Choices label="Revocation status" options={['Good', 'Revoked', 'Unknown']} value={revocation} onChange={v => change(() => setRevocation(v))}/></Experiment></>;
}
