import { useState } from 'react';
import { Actor, Arrow, Choices, Experiment, Status } from '../components/UI';
import type { SceneProps } from './Foundations';

const commands = [
  { title: 'Make a server key', input: 'Secure random input', output: 'server.key · PRIVATE', code: 'umask 077\nopenssl genpkey -algorithm RSA \\\n  -pkeyopt rsa_keygen_bits:2048 -out server.key', explanation: 'umask limits new file permissions. genpkey creates the private key from which the public key can be derived. Use a fresh private working directory.', result: 'Sample: a private key file is created. Its contents are deliberately not displayed.' },
  { title: 'Create a request', input: 'server.key · stays local', output: 'server.csr · public request', code: "openssl req -new -key server.key \\\n  -subj '/CN=server.example' \\\n  -addext 'subjectAltName=DNS:server.example' \\\n  -out server.csr\nopenssl req -in server.csr -noout -verify -subject", explanation: '-new creates a CSR. -key signs it with the server key. -addext requests a SAN; the issuer must review and approve it. -verify checks the request signature.', result: 'Sample: Certificate request self-signature verify OK. This is not domain validation or certificate issuance.' },
  { title: 'Issue an approved certificate', input: 'CSR + CA key/certificate + approved extensions', output: 'server.crt · public certificate', code: 'openssl x509 -req -in server.csr \\\n  -CA ca.crt -CAkey ca.key -CAcreateserial \\\n  -days 30 -sha256 -extfile server.ext \\\n  -out server.crt', explanation: 'Illustrative isolated lab only. Requires an existing protected CA with signing authority, and the server.ext file below. -CAcreateserial manages a local serial file; this is not a concurrent production CA service. The demo lifetime is arbitrary.', result: 'Sample: a CA-signed server certificate is created. The issuer’s key never becomes part of the output certificate.' },
  { title: 'Inspect the public card', input: 'server.crt', output: 'Readable identity fields', code: 'openssl x509 -in server.crt -noout \\\n  -subject -issuer -dates -serial \\\n  -ext subjectAltName', explanation: '-noout suppresses encoded certificate output. The other flags select public fields. Inspection is useful, but simply reading fields does not validate trust.', result: 'Sample: subject=CN=server.example\nissuer=CN=Demo CA\nX509v3 Subject Alternative Name: DNS:server.example' },
  { title: 'Check trust, purpose, and name', input: 'ca.crt + server.crt', output: 'Verification result', code: 'openssl verify -CAfile ca.crt \\\n  -purpose sslserver \\\n  -verify_hostname server.example server.crt', explanation: 'The lab CA directly signed this leaf. -CAfile supplies explicit public trust. -purpose checks server usage; -verify_hostname checks the service name. An intermediate hierarchy also needs its untrusted chain material, normally using -untrusted.', result: 'Sample when all checks pass: server.crt: OK\nA live TLS handshake must additionally prove the server has the matching private key.' },
];
const files = [
  { name: 'server.crt', kind: 'Public', content: '-----BEGIN CERTIFICATE-----\n[fictional certificate data]\n-----END CERTIFICATE-----', meaning: 'A public certificate. Safe to distribute for identity checks; its issuer still needs validation.' },
  { name: 'server.key', kind: 'Secret', content: '-----BEGIN PRIVATE KEY-----\n[contents intentionally omitted]\n-----END PRIVATE KEY-----', meaning: 'A private key. Keep it protected with its owner. A .pem extension would not make it public.' },
  { name: 'server.csr', kind: 'Public', content: '-----BEGIN CERTIFICATE REQUEST-----\n[fictional request data]\n-----END CERTIFICATE REQUEST-----', meaning: 'A signed request containing the public key and requested identity. It is not a finished certificate.' },
  { name: 'identity.p12', kind: 'Secret', content: '[binary PKCS#12 container]\nCertificates + private key in this fixture', meaning: 'This bundle includes a private key, so treat it as secret. PKCS#12 contents vary.' },
  { name: 'chain.pem', kind: 'Public', content: '-----BEGIN CERTIFICATE-----\n[issuing intermediate]\n-----END CERTIFICATE-----', meaning: 'This fixture is a public certificate chain bundle. The suffix alone never establishes the contents.' },
  { name: 'server.der', kind: 'Public', content: '[binary DER-encoded certificate]', meaning: 'The same kind of public certificate in binary form. DER is encoding, not encryption.' },
];
export function Files({ step, onInteract }: SceneProps) {
  const [selected, setSelected] = useState<number | null>(null); const [file, setFile] = useState(0); const [answer, setAnswer] = useState('');
  const command = commands[selected ?? [0, 0, 1, 3, 4][step]];
  return <><div className="scene"><div className="workbench-tabs" role="group" aria-label="Command stage">{commands.map((c, i) => <button className={command === c ? 'selected' : ''} key={c.title} onClick={() => { onInteract(); setSelected(i); }}>{i + 1}. {c.title}</button>)}</div><div className="file-flow"><span>{command.input}</span><span aria-hidden="true">→</span><strong>{command.output}</strong></div><div className="code-card"><div><span>OPENSSL 3 · ILLUSTRATIVE COMMAND</span><span>Read, don’t execute here</span></div><pre><code>{command.code}</code></pre></div><p className="command-explanation">{command.explanation}</p><pre className="sample-output">{command.result}</pre>{command === commands[2] && <details><summary>Required approved server.ext contents</summary><pre>{'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\nsubjectAltName=DNS:server.example\nsubjectKeyIdentifier=hash\nauthorityKeyIdentifier=keyid,issuer'}</pre><p>Create this configuration separately in a fresh lab directory. Protect ca.key and ensure the CA’s lifetime covers the leaf’s lifetime. These commands are learning examples, not a production issuance service.</p></details>}</div><Experiment><span className="field-label">Sort a file: can it be shared publicly?</span><div className="file-tray">{files.map((f, i) => <button className={file === i ? 'selected' : ''} onClick={() => { onInteract(); setFile(i); setAnswer(''); }} key={f.name}><span aria-hidden="true">▤</span>{f.name}</button>)}</div><pre className="file-preview">{files[file].content}</pre><Choices label="File classification" options={['Public', 'Secret']} value={answer} onChange={v => { onInteract(); setAnswer(v); }}/>{answer && <Status ok={answer === files[file].kind}>{files[file].meaning}</Status>}</Experiment></>;
}

const hops = [
  { label: 'GitLab → Praefect', client: 'GitLab client', server: 'Praefect', san: 'DNS:praefect.example', trust: 'Your private CA', auth: 'Praefect application token', detail: 'HAProxy forwards TCP bytes. The TLS endpoint is Praefect, so its certificate covers the service name requested by GitLab.' },
  { label: 'Praefect → Gitaly', client: 'Praefect', server: 'Gitaly-1', san: 'DNS:gitaly-1.example', trust: 'Your private CA', auth: 'Gitaly application token', detail: 'Praefect creates a new TLS connection and checks Gitaly’s identity. This is a separate handshake with separate traffic keys.' },
  { label: 'Praefect → RDS', client: 'Praefect', server: 'RDS database', san: 'DNS:database.example (fictional)', trust: 'AWS RDS public CA bundle', auth: 'Database credentials and permissions', detail: 'Use the actual RDS endpoint and its applicable AWS trust material in a real deployment. The private CA does not issue the RDS server certificate.' },
  { label: 'Gitaly → Gitaly', client: 'Gitaly-1', server: 'Gitaly-2', san: 'DNS:gitaly-2.example', trust: 'Your private CA', auth: 'Configured Gitaly application authentication', detail: 'A storage node can be a server on one connection and a client on another. Peer connections need their own identity checks.' },
];
export function GitLab({ step, onInteract }: SceneProps) {
  const [picked, setPicked] = useState<number | null>(null);
  const index = picked ?? [0, 0, 1, 2, 3][step]; const hop = hops[index];
  return <><div className="scene"><div className="scene-top"><span className="tag">ONE SYSTEM · SEPARATE TLS CONNECTIONS</span></div><div className="topology"><div>GitLab</div><span>→</span><div className="proxy">HAProxy<small>TCP passthrough</small></div><span>→</span><div>Praefect</div><span>→</span><div>Gitaly<small>↔ Gitaly peer</small></div></div><p className="branch">Praefect <span>↓ database TLS</span> RDS</p><div className="actor-row compact"><Actor kind="server" name={hop.client} caption="TLS client"/><Arrow>Separate protected connection</Arrow><Actor kind="server" name={hop.server} caption="TLS server" active/></div><dl className="hop-details"><div><dt>Identity to check</dt><dd>{hop.san}</dd></div><div><dt>Client trusts</dt><dd>{hop.trust}</dd></div><div><dt>Application gate</dt><dd>{hop.auth}</dd></div></dl><p className="little-note">{hop.detail}</p></div><Experiment><div className="choice-group" role="group" aria-label="Inspect connection">{hops.map((h, i) => <button key={h.label} className={index === i ? 'selected' : ''} aria-pressed={index === i} onClick={() => { onInteract(); setPicked(i); }}>{h.label}</button>)}</div><p>All names are fictional. A terminating load balancer would have a different certificate and TLS boundary.</p></Experiment></>;
}
